# https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
# https://hub.docker.com/r/tensorflow/tensorflow/
tensorflow:
    # zsjohny/tensorflow
    # registry.kuick.cn/cc/tensorflow:latest
    image: zsjohny/tensorflow
    container_name: tensorflow
    hostname: tensorflow
#    environment:
    volumes:
      - ../train:/notebooks/train
      - ../demo:/notebooks/demo
      - ../tensorflow-source/tensorflow/examples:/notebooks/example
      - ../tensorflow-source/tensorflow:/notebooks/tensorflow
      - ../models:/notebooks/models
      - ../data:/tmp
#      - ../config/:/.jupyter/
    ports:
      - 8888:8888
      - 6006:6006
    restart: always

