# https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
# https://hub.docker.com/r/tensorflow/tensorflow/
tensorflow:
    # zsjohny/tensorflow
    # registry.kuick.cn/cc/tensorflow:latest
    image: zsjohny/tensorflow
    container_name: tensorflow
    hostname: tensorflow
#    environment:
    volumes:
      - ../train:/notebooks/train
      - ../demo:/notebooks/demo
      - ../tensorflow-source/tensorflow/examples:/notebooks/example
      - ../tensorflow-source/tensorflow:/notebooks/tensorflow
      - ../models:/notebooks/models
      - ../mnist:/notebooks/mnist
      - ../data:/tmp
#      - ../config/:/.jupyter/
    ports:
      - 8888:8888
      - 6006:6006
    restart: always

mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YRSSx#FGgpzo
      - MYSQL_DATABASE=haixuelocal
  #      - MYSQL_USER=
  #      - MYSQL_PASSWORD=
  #      - MYSQL_ALLOW_EMPTY_PASSWORD=
  #      - MYSQL_RANDOM_ROOT_PASSWORD=
  #      - MYSQL_ONETIME_PASSWORD=
    ports:
      - 3306:3306
    restart: always

